version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ../infra/frontend/Dockerfile
    volumes:
      - ../frontend:/usr/src/app
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../infra/backend/Dockerfile
    volumes:
      - ../backend:/usr/src/app
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_DB=news
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U chat -d chat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped